// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD94_dp1lS-VRTni9axSeSDYM32hINjClM',
    appId: '1:285872124510:web:815cc83621f8bdec4cbacf',
    messagingSenderId: '285872124510',
    projectId: 'coffeesystem-f5071',
    authDomain: 'coffeesystem-f5071.firebaseapp.com',
    storageBucket: 'coffeesystem-f5071.firebasestorage.app',
    measurementId: 'G-T1XQSZKY1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOVUh9j7yxcH6Ig8NaGBbNEcoRwpR7R0M',
    appId: '1:285872124510:android:b3e398a3e01b38084cbacf',
    messagingSenderId: '285872124510',
    projectId: 'coffeesystem-f5071',
    storageBucket: 'coffeesystem-f5071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7D2EzgcUS-E26NTSNgfbwanZiComsqvQ',
    appId: '1:285872124510:ios:0e4c75560ca888a24cbacf',
    messagingSenderId: '285872124510',
    projectId: 'coffeesystem-f5071',
    storageBucket: 'coffeesystem-f5071.firebasestorage.app',
    iosBundleId: 'com.example.coffeeSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7D2EzgcUS-E26NTSNgfbwanZiComsqvQ',
    appId: '1:285872124510:ios:0e4c75560ca888a24cbacf',
    messagingSenderId: '285872124510',
    projectId: 'coffeesystem-f5071',
    storageBucket: 'coffeesystem-f5071.firebasestorage.app',
    iosBundleId: 'com.example.coffeeSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD94_dp1lS-VRTni9axSeSDYM32hINjClM',
    appId: '1:285872124510:web:e57abb6f73a242904cbacf',
    messagingSenderId: '285872124510',
    projectId: 'coffeesystem-f5071',
    authDomain: 'coffeesystem-f5071.firebaseapp.com',
    storageBucket: 'coffeesystem-f5071.firebasestorage.app',
    measurementId: 'G-4C5EDLBMDX',
  );
}
